name: pychecker

on: [push]

jobs:
  pychecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for Python code check
        uses: nanato12/pychecker@master
        with:
          path: './'
